function [U , sigma, image_vector, mean_A, X] = generateBadManifold()

S = {dir(sprintf('%s/*.png','TrainingImages/Boat64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Cabinet64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Cup64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Flashlight64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Car64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Chair64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Handle64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/HoseReel64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/ibook0164/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/imac0464/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/imac9864/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Keyboard64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/LED64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Light164/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Light264/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Mug64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Scooter64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/SprayBottle64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Stapler64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Trash64/UnProcessed'))};
    eigen_cat = zeros(16384, 1);


for k = 1:20
     [U , sigma, image_vector, mean_A, X] = generateSingleManifold(S(k));
     w = ComputeER(image_vector, sigma, .95);
     s = size(eigen_cat,2)+1;
     eigen_cat = [ eigen_cat(:,:) , U(:, 1:k)];
end
eigen_cat(:, 1) = []; % trim off inital zero.

[U, sigma, ~] = svd(eigen_cat, 'econ');





end