function [U , sigma, image_vector, mean_A, X] = generateManifold()

S = {dir(sprintf('%s/*.png','TrainingImages/Boat64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Cabinet64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Cup64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Flashlight64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Car64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Chair64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Handle64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/HoseReel64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/ibook0164/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/imac0464/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/imac9864/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Keyboard64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/LED64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Light164/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Light264/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Mug64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Scooter64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/SprayBottle64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Stapler64/UnProcessed')),...
    dir(sprintf('%s/*.png','TrainingImages/Trash64/UnProcessed'))};

image_mean = zeros(128,128);

for k = 1:20
    cell = S{k};
    for i = 1:128
        F = cell(i);
        I = imread(strcat(F.folder,'\',F.name));
        if size(I,3) ~= 1
            I = rgb2grey(I);
        end
        I = im2double(I);
        
        image_vector(((k-1)*128 + i), :) = I(:);
        image_mean = image_mean + I;
    end
end

A = image_mean / (128 * 20);

figure;
imshow(A,[]);

mean_A = A(:);


X = image_vector - mean_A';


[U, sigma, ~] = svd(X', 'econ');





end